"""credit card fields

Revision ID: 3fe05f650a4d
Revises: 852d7a61ba3d
Create Date: 2026-08-24 14:42:55.405904
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '3fe05f650a4d'
down_revision: str | None = '852d7a61ba3d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Columns are nullable and card-only; existing accounts are untouched.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('credit_limit', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('accounts', sa.Column('statement_balance', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('accounts', sa.Column('statement_closing_day', sa.SmallInteger(), nullable=True))
    op.add_column('accounts', sa.Column('payment_due_day', sa.SmallInteger(), nullable=True))
    op.add_column('accounts', sa.Column('minimum_payment', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('accounts', sa.Column('interest_rate', sa.Numeric(precision=8, scale=5), nullable=True))
    op.add_column('accounts', sa.Column('expiry_month', sa.SmallInteger(), nullable=True))
    op.add_column('accounts', sa.Column('expiry_year', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###

    op.create_check_constraint(
        "credit_limit_non_negative", "accounts", "credit_limit IS NULL OR credit_limit >= 0"
    )
    op.create_check_constraint(
        "statement_closing_day_range",
        "accounts",
        "statement_closing_day IS NULL OR statement_closing_day BETWEEN 1 AND 31",
    )
    op.create_check_constraint(
        "payment_due_day_range",
        "accounts",
        "payment_due_day IS NULL OR payment_due_day BETWEEN 1 AND 31",
    )
    op.create_check_constraint(
        "expiry_month_range", "accounts", "expiry_month IS NULL OR expiry_month BETWEEN 1 AND 12"
    )


def downgrade() -> None:
    op.drop_constraint("ck_accounts_expiry_month_range", "accounts", type_="check")
    op.drop_constraint("ck_accounts_payment_due_day_range", "accounts", type_="check")
    op.drop_constraint("ck_accounts_statement_closing_day_range", "accounts", type_="check")
    op.drop_constraint("ck_accounts_credit_limit_non_negative", "accounts", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'expiry_year')
    op.drop_column('accounts', 'expiry_month')
    op.drop_column('accounts', 'interest_rate')
    op.drop_column('accounts', 'minimum_payment')
    op.drop_column('accounts', 'payment_due_day')
    op.drop_column('accounts', 'statement_closing_day')
    op.drop_column('accounts', 'statement_balance')
    op.drop_column('accounts', 'credit_limit')
    # ### end Alembic commands ###
