"""planning: planned transactions, recurrence, reminders, notifications

Revision ID: 7e6359b3c1b6
Revises: 3fe05f650a4d
Create Date: 2026-08-24 15:04:02.206406
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '7e6359b3c1b6'
down_revision: str | None = '3fe05f650a4d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('PLANNED_DUE', 'PLANNED_OVERDUE', 'CARD_PAYMENT_DUE', 'LOAN_DUE', 'SYSTEM', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('related_entity_type', sa.Enum('PLANNED_TRANSACTION', 'LOAN', 'CREDIT_CARD', 'FAMILY_INVITATION', name='reminder_entity'), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('reminders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('PLANNED_TRANSACTION', 'LOAN', 'CREDIT_CARD', 'FAMILY_INVITATION', name='reminder_entity'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'CANCELLED', 'FAILED', name='reminder_status'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reminders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    op.create_index('ix_reminders_due', 'reminders', ['status', 'remind_at'], unique=False)
    op.create_index(op.f('ix_reminders_entity_id'), 'reminders', ['entity_id'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('recurring_rules',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('planned_type', sa.Enum('INCOME', 'EXPENSE', name='planned_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='recurrence_frequency'), nullable=False),
    sa.Column('interval_value', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_occurrence_date', sa.Date(), nullable=True),
    sa.Column('occurrence_hour', sa.Integer(), nullable=False),
    sa.Column('reminder_days_before', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ENDED', name='recurring_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_recurring_rules_recurring_amount_positive')),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name=op.f('ck_recurring_rules_end_after_start')),
    sa.CheckConstraint('interval_value >= 1', name=op.f('ck_recurring_rules_interval_at_least_one')),
    sa.CheckConstraint('occurrence_hour BETWEEN 0 AND 23', name=op.f('ck_recurring_rules_occurrence_hour_range')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_recurring_rules_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_recurring_rules_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_recurring_rules_created_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_rules'))
    )
    op.create_index(op.f('ix_recurring_rules_next_occurrence_date'), 'recurring_rules', ['next_occurrence_date'], unique=False)
    op.create_index('ix_recurring_status_next', 'recurring_rules', ['status', 'next_occurrence_date'], unique=False)
    op.create_table('planned_transactions',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('planned_type', sa.Enum('INCOME', 'EXPENSE', name='planned_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurrence_date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UPCOMING', 'DUE', 'COMPLETED', 'MISSED', 'CANCELLED', 'SKIPPED', name='planned_status'), nullable=False),
    sa.Column('source', sa.Enum('ONE_TIME', 'RECURRING', name='planned_source'), nullable=False),
    sa.Column('recurring_rule_id', sa.UUID(), nullable=True),
    sa.Column('completed_transaction_id', sa.UUID(), nullable=True),
    sa.Column('original_expected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_key', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_planned_transactions_planned_amount_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_planned_transactions_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_planned_transactions_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_transaction_id'], ['transactions.id'], name=op.f('fk_planned_transactions_completed_transaction_id_transactions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_planned_transactions_created_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurring_rule_id'], ['recurring_rules.id'], name=op.f('fk_planned_transactions_recurring_rule_id_recurring_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planned_transactions')),
    sa.UniqueConstraint('recurring_rule_id', 'occurrence_date', name='one_occurrence_per_rule_per_day')
    )
    op.create_index('ix_planned_account_expected', 'planned_transactions', ['account_id', 'expected_at'], unique=False)
    op.create_index('ix_planned_status_expected', 'planned_transactions', ['status', 'expected_at'], unique=False)
    op.create_index(op.f('ix_planned_transactions_expected_at'), 'planned_transactions', ['expected_at'], unique=False)
    op.create_index(op.f('ix_planned_transactions_recurring_rule_id'), 'planned_transactions', ['recurring_rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planned_transactions_recurring_rule_id'), table_name='planned_transactions')
    op.drop_index(op.f('ix_planned_transactions_expected_at'), table_name='planned_transactions')
    op.drop_index('ix_planned_status_expected', table_name='planned_transactions')
    op.drop_index('ix_planned_account_expected', table_name='planned_transactions')
    op.drop_table('planned_transactions')
    op.drop_index('ix_recurring_status_next', table_name='recurring_rules')
    op.drop_index(op.f('ix_recurring_rules_next_occurrence_date'), table_name='recurring_rules')
    op.drop_table('recurring_rules')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_entity_id'), table_name='reminders')
    op.drop_index('ix_reminders_due', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###

    # Alembic drops the tables but leaves the enum types behind, which makes
    # the migration non-reversible: re-running upgrade fails with
    # "type already exists". They have to go too.
    for enum_name in (
        "planned_status",
        "planned_source",
        "planned_type",
        "recurrence_frequency",
        "recurring_status",
        "reminder_status",
        "reminder_entity",
        "notification_type",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
